# cloudbuild.complete.yaml - 完整的Cloud Build配置
steps:
  # 步骤1: 构建Docker镜像
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/autocheckin:$COMMIT_SHA"
      - "."

  # 步骤2: 推送Docker镜像到Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/autocheckin:$COMMIT_SHA"

  # 步骤3: 部署到Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "autocheckin"
      - "--image"
      - "gcr.io/$PROJECT_ID/autocheckin:$COMMIT_SHA"
      - "--region"
      - "asia-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--timeout"
      - "900"
      - "--concurrency"
      - "1"
      - "--set-env-vars"
      - "NODE_ENV=production"

images:
  - "gcr.io/$PROJECT_ID/autocheckin:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY 