steps:
  # 构建Docker镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/autocheckin', '.']
  
  # 推送镜像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autocheckin']

images:
  - 'gcr.io/$PROJECT_ID/autocheckin'

options:
  logging: CLOUD_LOGGING_ONLY 